# Views and Copies

In [31]:
 import numpy as np


In [32]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])


In [33]:
su_casa = mi_casa


# Same or Different?


In [34]:
#reference equality or no shallow  copy
su_casa is mi_casa

True

In [35]:
id(mi_casa)

1506968160848

In [36]:
id(su_casa)

1506968160848

In [37]:
#value inqulaty 
mi_casa==su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [38]:
su_casa[4]=1010

In [39]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [40]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

### Let's create new array with same value of mi_case

In [41]:
tree_house = np.array([-45, -31, -12, 0, 1010, 25, 51, 99])

In [42]:
tree_house == mi_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [43]:
id(tree_house)

1506968166224

In [44]:
id(mi_casa)


1506968160848

In [45]:
tree_house[0]=214

In [46]:
tree_house

array([ 214,  -31,  -12,    0, 1010,   25,   51,   99])

In [47]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

# View: a shallow copy

In [48]:
farm_house = tree_house.view() 
farm_house.shape = (2,4)


In [49]:
id(tree_house)


1506968166224

In [50]:
id(farm_house)

1506968169680

In [51]:
farm_house

array([[ 214,  -31,  -12,    0],
       [1010,   25,   51,   99]])

In [52]:
tree_house

array([ 214,  -31,  -12,    0, 1010,   25,   51,   99])

In [60]:
tree_house[3]=-111
tree_house

array([ 214,  -31,  -12, -111, 1010,   25,   51,   99])

In [61]:
farm_house


array([[ 214,  -31,  -12, -111],
       [1010,   25,   51,   99]])

In [66]:
farm_house[0,3]

-111

# Deep copy

In [69]:
dog_house=np.copy(tree_house)
dog_house[0]=-222
dog_house

array([-222,  -31,  -12, -111, 1010,   25,   51,   99])

In [70]:
tree_house  # not change

array([ 214,  -31,  -12, -111, 1010,   25,   51,   99])

In [72]:
tree_house.shape=(2,2,2)
tree_house

array([[[ 214,  -31],
        [ -12, -111]],

       [[1010,   25],
        [  51,   99]]])

In [73]:
new_arr=np.copy(tree_house)   #two Dim
new_arr

array([[[ 214,  -31],
        [ -12, -111]],

       [[1010,   25],
        [  51,   99]]])

In [79]:
new_arr[0,1,1]=1010   # new_arr[0][1][1]
new_arr

array([[[ 214,  -31],
        [ -12, 1010]],

       [[1010,   25],
        [  51,   99]]])

In [78]:
tree_house  # not change

array([[[ 214,  -31],
        [ -12, -111]],

       [[1010,   25],
        [  51,   99]]])