You might wonder that numpy.linalg also provides us with functions that help to solve algebraic equations, so should we use numpy.linalg or scipy.linalg? The scipy.linalg contains all the functions that are in numpy.linalg, in addition it also has some other advanced functions that are not in numpy.linalg such as functions related to LU decomposition and the Schur decomposition, multiple ways of calculating the pseudoinverse, and matrix transcendentals such as the matrix logarithm. Another advantage of using scipy.linalg over numpy.linalg is that it has efficient low level implementations of standard linear algebra algorithms, so it's faster than numpy.


# Solve Linear Equations

In [30]:
import numpy as np
from scipy import linalg
from scipy import *

In [31]:

# We are trying to solve a linear algebra system which can be given as 
#x + 2y 3z = -3
#2x 5y+4z 13
#5x + 4y-z = 5
#We will find values of x,y and z for which all these equations are zero #Also finally we will check if the values are right by substituting them 
#in the equations
# Creating input array
a = np.array([[1, 2, 3], [2, -5, 4], [5, 4, -1]])
# Solution Array
b = np.array([[-3], [13], [5]])
# Solve the Linear algebra
X = linalg.solve(a, b)
# Print results
print(X)
# Checking Results must be zero
print("Checking Results, must be zero")
print(a.dot(X)-b)

[[ 2.5]
 [-2. ]
 [-0.5]]
Checking Results, must be zero
[[0.]
 [0.]
 [0.]]


In [32]:
type(X)

numpy.ndarray

# Finding a determinant of a square matrix


In [33]:
#importing the scipy and numpy packages 2 from scipy import linalg
import numpy as np

#Declaring the numpy array
A = np.array([[1,2,9], [3,4,8],[7,8,4]]) 
#Passing the values to the det function 
x = linalg.det(A)
#printing the result
print('Determinant of \n{} \n is {}'.format(A,x))


Determinant of 
[[1 2 9]
 [3 4 8]
 [7 8 4]] 
 is 3.9999999999999902


# Eigenvalues and Eigenvectors

In [34]:
#importing the scipy and numpy packages 2 from scipy import linalg
import numpy as np
#Declaring the numpy array

#importing the scipy and numpy packages from scipy import linalg import numpy as np
#Declaring the numpy array
A = np.array([[2,1,-2], [1,0,0], [0,1,0]])
#Passing the values to the eig function 
values, vectors = linalg.eig(A)
#printing the result for eigenvalues 
print(values)
#printing the result for eigenvectors 
print(vectors)

[-1.+0.j  2.+0.j  1.+0.j]
[[-0.57735027 -0.87287156  0.57735027]
 [ 0.57735027 -0.43643578  0.57735027]
 [-0.57735027 -0.21821789  0.57735027]]


# Performance of SciPy vs. NumPy
Who will win?!


In [35]:
coeff_array = np.array([[2, 5, 4], [1, -1, 4], [-4, 3, -1]])
coeff_array.shape

(3, 3)

In [36]:
rh_side_array=np.array([[10], [20], [5]])
rh_side_array.shape


(3, 1)

In [37]:
import time
start_time =time.time()
np.linalg.solve(coeff_array, rh_side_array)
print(''' Executed Time to solve by NumPy is %f seconds'''% (time.time() -start_time))

 Executed Time to solve by NumPy is 0.001001 seconds


In [38]:
import time
from scipy import linalg
start_time =time.time()
linalg.solve(coeff_array, rh_side_array)
print(''' Executed Time to solve by SciPy is %f seconds''' % (time.time() -start_time))

 Executed Time to solve by SciPy is 0.000989 seconds
