
# Adding and Removing Elements from NumPy Arrays 
- append 
- horizontal stacking
-  vertical stacking
-  insert
-  delete

In [34]:
import numpy as np

# add function 

In [35]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
b=np.append(a,[1,2,3,4])   # alwas  return one D array  ,a not change 
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  1,  2,  3,  4])

In [37]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

axis:
` 2D`
    axise -> rows
    axis1 --> columns
`3D `
    axise --> depth
    axis1 --> rows
    axis2 --> columns
############‡
a (2,3,4)
c (2,3,4)
appened based on axise0: 4*3*4 
appened based on axis1: 2*6*4
appened based on axis2: 2*3*8

#######


In [38]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
a=np.arange(24).reshape(2,3,4)*10+3
a

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [40]:
res=np.append(a,c,axis=0) # incease depth 
res

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]],

       [[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [41]:
res=np.append(a,c,axis=1) # incease row 
res

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [42]:
res=np.append(a,c,axis=1) # incease col 
res

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [43]:
np.append(a,c)    # return 1D

array([  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123,
       133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23])

In [44]:
np.append(a,c,axis=2).shape

(2, 3, 8)

# Ex2

In [45]:
z=np.arange(12).reshape((1,3,4))
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [46]:
#c-->(2,3,4)
#z--> (1.3,4)
np.append(c,z,axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
#c-->(2,3,4)
#z--> (1.3,4)
np.append(c,z,axis=0)

In [ ]:
np.append(c,z)

In [ ]:
#not similar dimensions, default behaviour 
data1= np.array([[1,2,3], [4, 5, 6]]) # 2*3 
data2 = np.array([7,8,9])# 3
np.append(data1, data2)

In [ ]:
# not similar dimensions, by defining an axis :( np.append(datal, data2, axis=1)
np.append(data1, data2,axis=0)


# stack function 
work  based on  second access "axis=1"  if use multidimantion array

In [54]:
a_1d=a.ravel()
c_1d=c.ravel()
a_1d

array([  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123,
       133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233])

In [55]:

my_1d_hstack=np.hstack((a_1d,c_1d))
my_1d_hstack

array([  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123,
       133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23])

In [62]:
a_2d=a_1d.reshape((6,4))
c_2d=c_1d.reshape(6,4)
my_2d_hstack=np.hstack((a_2d,c_2d))
my_2d_hstack

array([[  3,  13,  23,  33,   0,   1,   2,   3],
       [ 43,  53,  63,  73,   4,   5,   6,   7],
       [ 83,  93, 103, 113,   8,   9,  10,  11],
       [123, 133, 143, 153,  12,  13,  14,  15],
       [163, 173, 183, 193,  16,  17,  18,  19],
       [203, 213, 223, 233,  20,  21,  22,  23]])

In [63]:
my_2d_hstack.shape

(6, 8)

In [71]:
# number of rows isn't the same, but here's an issue as it's not axis1
np.hstack((a_2d[:4],c_2d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 6

In [70]:
#number of columns isn't the same, but no issue as it's axis1
my_2d_h_stack_2 = np.hstack ((a_2d,c_2d[:,:3]))
my_2d_h_stack_2.shape


(6, 7)

In [64]:
# a -->(2,3,4)
#c-->(2,3,4)
my_3d_hstack=np.hstack((a,c))   # by default work on axis=1
my_3d_hstack

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [65]:
my_3d_hstack.shape

(2, 6, 4)

In [74]:
# number of rows isn't the same (3D), but no issue as it's axis1
my_3d_h_stack_2=np.hstack ((a,c[:,:2])) 
my_3d_h_stack_2.shape

(2, 5, 4)

In [75]:
#depth isn't the same (3D), but here's an issue as it's not axis1 
np.hstack ((a,c[:1]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [76]:
# it's illogical to try with arrays that have different dimensions !! 
np.hstack((a_2d, a))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

# vstack
working based on the first axis (axis0) if there's more than one dimension

In [77]:
#Let's try on 1-D
my_1d_v_stack= np.vstack ((a_1d,c_1d)) # input 1D array  output 2Darray 
my_1d_v_stack

array([[  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123,
        133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]])

In [78]:
my_1d_v_stack.shape

(2, 24)

In [80]:
# tey with 2D array 
my_2d_vstach=np.vstack((a_2d,c_2d))
my_2d_vstach

array([[  3,  13,  23,  33],
       [ 43,  53,  63,  73],
       [ 83,  93, 103, 113],
       [123, 133, 143, 153],
       [163, 173, 183, 193],
       [203, 213, 223, 233],
       [  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [81]:
my_2d_vstach.shape

(12, 4)

In [85]:
#number of rows isn't the same, but no issue as it's axise 
my_2d_vstack_2 = np.vstack ((a_2d,c_2d[:4]))
my_2d_vstack_2.shape



(10, 4)

In [83]:
#number of columns isn't the same, but here's an issue as it's not axise
np.vstack((a_2d[:,:3],c_2d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [86]:
#Let's try on 3-D arrays
my_3d_v_stack=np.vstack((a,c))  #a,b-->(2,3,4)
my_3d_v_stack                   #(4,3,4)


array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]],

       [[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [89]:
# depth isn't the same (3D), but no issue as it's axise 
my_3d_v_stack_2 = np.vstack ((a,c[:1]))
my_3d_v_stack_2.shape


(3, 3, 4)

In [90]:
# number of rows isn't the same (3D), but here's an issue as it's not axise
np.vstack((a,c[:,:1]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

# Insert function

In [94]:
# ex on  scaler 
array_after_insert =np.insert(c, 1, 444, axis=0) #1 is position ,444 is vlaue 
array_after_insert

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [96]:
# insert array instead of a scalar value
to_be_inserted =np.arange(12).reshape(3,4)
array_after_insert_2 = np.insert(c, 2, to_be_inserted, axis=0) 
array_after_insert_2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [98]:
# insert array instead of a scalar value
to_be_inserted =np.arange(12).reshape(4,3)
array_after_insert_2 = np.insert(c, 0, to_be_inserted, axis=0) 
array_after_insert_2

ValueError: could not broadcast input array from shape (1,4,3) into shape (1,3,4)

In [101]:
np.insert(c,2,4444,axis=1)

array([[[4444, 4444, 4444, 4444],
        [   0,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[4444, 4444, 4444, 4444],
        [  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [102]:
np.insert(c,2,4444,axis=2)

array([[[   0,    1, 4444,    2,    3],
        [   4,    5, 4444,    6,    7],
        [   8,    9, 4444,   10,   11]],

       [[  12,   13, 4444,   14,   15],
        [  16,   17, 4444,   18,   19],
        [  20,   21, 4444,   22,   23]]])

In [103]:
d=np.empty(c.shape)
np.copyto(d,c)             # see next 
d

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [105]:
np.delete(d,0,axis=0)  # delete is the opposite to  insert 

array([[[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [106]:
np.delete(d,1,axis=2)  # delete is the opposite to  insert 

array([[[ 0.,  2.,  3.],
        [ 4.,  6.,  7.],
        [ 8., 10., 11.]],

       [[12., 14., 15.],
        [16., 18., 19.],
        [20., 22., 23.]]])