# Read Dataset

for more information, please see: https://numpy.org/doc/1.20/reference/generated/numpy.genfromtxt.html


In [7]:
import numpy as np
arr = np.genfromtxt("simple_dataset_to_read.csv", delimiter="|") 
arr


array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

# Write a dataset


for more information, please see: https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html


In [34]:
new_arr= arr*50 -10
new_arr

array([[-10.,  40.,  90., 140., 190., 240., 290., 340., 390., 440., 490.],
       [ 40.,  90., 140., 190., 240., 290., 340., 390., 440., 490., 540.],
       [ 90., 140., 190., 240., 290., 340., 390., 440., 490., 540., 590.],
       [140., 190., 240., 290., 340., 390., 440., 490., 540., 590., 640.],
       [190., 240., 290., 340., 390., 440., 490., 540., 590., 640., 690.],
       [240., 290., 340., 390., 440., 490., 540., 590., 640., 690., 740.],
       [290., 340., 390., 440., 490., 540., 590., 640., 690., 740., 790.],
       [340., 390., 440., 490., 540., 590., 640., 690., 740., 790., 840.],
       [390., 440., 490., 540., 590., 640., 690., 740., 790., 840., 890.],
       [440., 490., 540., 590., 640., 690., 740., 790., 840., 890., 940.],
       [490., 540., 590., 640., 690., 740., 790., 840., 890., 940., 990.]])

In [23]:

#np.savetxt('exported_dataset.csv', new_arr, delimiter=',')
#np.savetxt('exported_dataset.csv', new_arr, delimiter=',', fmt='%. 2e')
np.savetxt('exported_dataset.csv', new_arr, delimiter=',', fmt='%d',header="")

In [31]:
new_arr_2= np.arange(50, dtype='int64')
new_arr_2.shape = (5,10)
new_arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]], dtype=int64)

In [32]:
np.savetxt('exported_dataset_2.csv', new_arr, delimiter=',', fmt='%d',header="")

In [36]:
new_arr.shape

(11, 11)

# lets try 3D array

In [37]:
new_arr=np.insert(new_arr,1,1,axis=1)

In [38]:
new_arr.shape

(11, 12)

In [41]:
new_arr.shape=(4,11,3)
new_arr

array([[[-10.,   1.,  40.],
        [ 90., 140., 190.],
        [240., 290., 340.],
        [390., 440., 490.],
        [ 40.,   1.,  90.],
        [140., 190., 240.],
        [290., 340., 390.],
        [440., 490., 540.],
        [ 90.,   1., 140.],
        [190., 240., 290.],
        [340., 390., 440.]],

       [[490., 540., 590.],
        [140.,   1., 190.],
        [240., 290., 340.],
        [390., 440., 490.],
        [540., 590., 640.],
        [190.,   1., 240.],
        [290., 340., 390.],
        [440., 490., 540.],
        [590., 640., 690.],
        [240.,   1., 290.],
        [340., 390., 440.]],

       [[490., 540., 590.],
        [640., 690., 740.],
        [290.,   1., 340.],
        [390., 440., 490.],
        [540., 590., 640.],
        [690., 740., 790.],
        [340.,   1., 390.],
        [440., 490., 540.],
        [590., 640., 690.],
        [740., 790., 840.],
        [390.,   1., 440.]],

       [[490., 540., 590.],
        [640., 690., 740.],
        [790.,

In [42]:
new_arr.shape

(4, 11, 3)

In [44]:
np.savetxt('exported_multidim_dataset_2.csv', new_arr, delimiter=',', fmt='%d',header="")  # can not write 3d

ValueError: Expected 1D or 2D array, got 3D array instead

# let's try another function

In [45]:
np.save( 'exported_multidim_dataset.npy', new_arr)


In [46]:
arr = np.load( 'exported_multidim_dataset.npy') 


In [47]:
arr.shape


(4, 11, 3)

In [48]:
arr

array([[[-10.,   1.,  40.],
        [ 90., 140., 190.],
        [240., 290., 340.],
        [390., 440., 490.],
        [ 40.,   1.,  90.],
        [140., 190., 240.],
        [290., 340., 390.],
        [440., 490., 540.],
        [ 90.,   1., 140.],
        [190., 240., 290.],
        [340., 390., 440.]],

       [[490., 540., 590.],
        [140.,   1., 190.],
        [240., 290., 340.],
        [390., 440., 490.],
        [540., 590., 640.],
        [190.,   1., 240.],
        [290., 340., 390.],
        [440., 490., 540.],
        [590., 640., 690.],
        [240.,   1., 290.],
        [340., 390., 440.]],

       [[490., 540., 590.],
        [640., 690., 740.],
        [290.,   1., 340.],
        [390., 440., 490.],
        [540., 590., 640.],
        [690., 740., 790.],
        [340.,   1., 390.],
        [440., 490., 540.],
        [590., 640., 690.],
        [740., 790., 840.],
        [390.,   1., 440.]],

       [[490., 540., 590.],
        [640., 690., 740.],
        [790.,

# it`s good  now :)